### Makefile for www/Steve_Savitzky/Tools/TeX
#	$Id: Makefile,v 1.4 2006-05-21 03:24:39 steve Exp $
# 	COPYRIGHT 1998, HyperSpace Express

TOPDIR=../../../../..
MYNAME=TeX
DOTDOT=www/Steve_Savitzky/Tools
SRCDIR=../../../.

FILES= \
	$(wildcard *.html) $(wildcard *.ps) $(wildcard *.flk) \
	$(wildcard *.tex) $(wildcard *.sty) \
	$(wildcard *.pl) Makefile.txt .htaccess \
	flktran.pl index.pl chord.c Makefile.txt \
	song.sty fullpage.sty twocolumns.sty 1song.tex zongbook.sty

MF_DIR=$(TOPDIR)/Config/makefiles
include $(MF_DIR)/file.make
include $(MF_DIR)/webdir.make

