#!/bin/sh
# Called once after update, with list of refs pushed in the arguments.

for ref in $*; do
    if [[ $ref =~ .*/master$ ]]; then
	unexport GIT_DIR
	repo=`pwd`
	name=`basename $repo .git`
	# This works because the .../vv and .../git trees have the same layout
	dest=`dirname $repo | sed -e 's/git/vv/'`/$name
	if [ -d $dest ]; then (cd $dest
	    echo Deploying master to $dest from $repo
	    git pull --ff-only $repo
	    if [ -e config.make ] &&  {grep -q post-deployment config.make}; then
		make post-deployment
	    fi
	    )
	else 
	    echo Not deploying because $dest does not exist.
	fi
    else
        echo "Ref $ref successfully received.  Not deploying because not master."
    fi
done
