#!/bin/sh
# Set post-update deployment hooks in git repositories

# Assumes Tools is a symlink in ~/git

HOOKS="post-update"

for repo in $*; do
    (
	cd $repo
	pwd=`pwd`
	name=`basename $pwd .git`
	dest=`dirname $pwd | sed -e 's/git/vv/'`/$name
	if [ -d $dest ]; then
	    echo Installing hooks in $pwd/hooks.
	    cd hooks
	    d=../../Tools/deployment
	    while [ ! -d $d ]; do d=../$d; done
	    # force in case things moved
	    for hook in $HOOKS; do ln -sf $d/$hook .; done
	else
	    echo $dest does not exist.  Remove old hooks if necessary
	fi
    )
done
