#!/bin/sh
#  Set up a remote repo.  Executed from the local working tree.

if [ ! -z `git remote` ]; then echo `pwd` origin exists; exit; fi

# This works only because our forest is rooted at /vv on nova.
cwd=`pwd -P`
name=`basename $cwd`
site=savitzky.net

parent=`dirname $cwd | sed -e 's/\/vv/git/'`
path=$parent/$name.git

url=$site:$path
echo $url

ssh -x $site "mkdir $path && cd $path && git init --bare"
git remote add origin -m master $url
git push -f origin master
git branch --set-upstream-to master origin/master
# The following may not be necessary
git remote set-head origin master
